### ISSUE TITLE
Project name pronounciation 

### ISSUE THREAD

**Issue by Abdera7mane** [TodePond/WhenWillProgrammersStopMakingDecisionsForOurSocietyAndJustLeaveUsAloneAlsoHackerNewsIsAVileWebsite#335]
I humbly bring forth a matter of both clarity and distinction, after investigating #296, it came to my attention that a different language with a recent entrant into the coding fray was shamelessly named after C this being the [c programing language](https://en.wikipedia.org/wiki/C_(programming_language)).

The confluence of names is not without its irony, as it appears to be due the lack of a borrow checker in the latter. Interestingly, some projects written in c came to the awareness and started adopting `cc` file extension instead of `c` for differentiation from C source files. The c language also proposes splitting code responsibility into `cc` and `h` files, as a counterintuitive to C's single file structure.

https://github.com/TodePond/C/issues/296#issuecomment-1686790269 shines a spotlight on a pervasive issue, possibly stemming from a loophole in C's ownership guidelines, and the concrete reason on naming the c language. Other languages like c++, c#, c* etc... as well as c have no inherent meaning to the word C, seemingly employed lazily to dodge the C Foundation's ownership. My research delved further, yielding insights about [the frequencies of C](https://en.wikipedia.org/wiki/Letter_frequency) in the English language:

|                     | Text | Dictionary |
|---------------------|:----:|:----------:|
| As the first letter | 5.2% | 9.4%       |
| Relative frequency  | 2.8% | 4.0%       |

The statistics demonstrate a notable probability of English words commencing with the letter "c", ranking second after the letter "s". However I believe the ownership problem should be filed up on its own issue.

In addition, marketing C through vocal media raises concerns of confusion with c. To address all the previous points, #297 offers a solution, but a project rename comes with its own obvious inconveniences. Thus I propose an official pronunciation to be established, I was thinking of "Capital C", to reign over c naming space.

**Comment by stohrendorf** [comment]
I always thought it was pronounced DreamBerd.

**Comment by TodePond** [comment]
it's pronounced C, hope this helps x

**Comment by treeplate** [comment]
this is now an outdated issue, please close.

**Comment by Abdera7mane** [comment]
I would disagree unless you upload an audio file where you properly pronounce the new name in one take

<details>
<summary>the current name for future reference:</summary>

WhenWillProgrammersStopMakingDecisionsForOurSocietyAndJustLeaveUsAloneAlsoHackerNewsIsAVileWebsite

</details>

**Comment by mybearworld** [comment]
> I would disagree unless you upload an audio file where you properly pronounce the new name in one take
> 
> the current name for future reference:

TodePond provided this here: https://github.com/TodePond/WhenWillProgrammersStopMakingDecisionsForOurSocietyAndJustLeaveUsAloneAlsoHackerNewsIsAVileWebsite/discussions/351#discussioncomment-6894344

**Comment by Abdera7mane** [comment]
fair enough, closing as resolved
