### ISSUE TITLE
The installation instructions don't work anymore

### ISSUE THREAD

**Issue by mybearworld** [TodePond/WhenWillProgrammersStopMakingDecisionsForOurSocietyAndJustLeaveUsAloneAlsoHackerNewsIsAVileWebsite#353]
The video just returns a 404

**Comment by Joshix-1** [comment]
yes, the video should be put in the repository

**Comment by Joshix-1** [comment]
I've tried and failed. https://github.com/Joshix-1/WhenWillProgrammersStopMakingDecisionsForOurSocietyAndJustLeaveUsAloneAlsoHackerNewsIsAVileWebsite/tree/installation

I don't know what magic @TodePond did to the video to make it work, but I'm not capable of it

**Comment by TodePond** [comment]
Just paste the image in I think! You could then swap out the pasted link with a static asset that you add to the repo

**Comment by mybearworld** [comment]
Yeah, but that doesn't work - it specifically only works with copy-pasted video

**Comment by Joshix-1** [comment]
Broken link is gone.

**Comment by TodePond** [comment]
Well done everyone!
