### ISSUE TITLE
well, now i don't know how to use it, because of the fyp

### ISSUE THREAD

**Issue by loglot** [TodePond/WhenWillProgrammersStopMakingDecisionsForOurSocietyAndJustLeaveUsAloneAlsoHackerNewsIsAVileWebsite#356]

**Comment by mybearworld** [comment]
If the For You Page doesn't include the information, you don't need the information. That's the point of the For You Page.

**Comment by loglot** [comment]
> If the For You Page doesn't include the information, you don't need the information. That's the point of the For You Page.

alright
